
// This class is autogenerated by ./autogen_res.py.
class AssetsList
{
    static list(){
        let assets = new Array();
        assets.push("gfx/stompy.png");
        assets.push("gfx/rabbit_house.png");
        assets.push("gfx/platform_left_right.png");
        assets.push("gfx/door_next_level.png");
        assets.push("gfx/spike_ceiling_falling.png");
        assets.push("gfx/unknown.png");
        assets.push("gfx/doggy.png");
        assets.push("gfx/hero_r0.png");
        assets.push("gfx/sign_its_safe.png");
        assets.push("gfx/flying_fire.png");
        assets.push("gfx/sign_danger.png");
        assets.push("gfx/hero_l0.png");
        assets.push("gfx/spike_man.png");
        assets.push("gfx/ground_lr2.png");
        assets.push("gfx/mr_spore.png");
        assets.push("gfx/spikes.png");
        assets.push("gfx/block_fall_on_touch.png");
        assets.push("gfx/tombstone.png");
        assets.push("gfx/smoke_dust.png");
        assets.push("gfx/spike_ceiling.png");
        assets.push("gfx/l0_splash.png");
        assets.push("gfx/lava.png");
        assets.push("gfx/squished.png");
        assets.push("gfx/canon_bullet_left.png");
        assets.push("gfx/ground_lr.png");
        assets.push("gfx/canon_horizontal.png");
        assets.push("levels/l_01.json");
        assets.push("levels/l_00_rabbit_in_house.json");
        assets.push("levels/l_03.json");
        assets.push("levels/l_02.json");
        assets.push("levels/l_04.json");
        assets.push("levels/l_99_rabbit_in_safe_house.json");
        assets.push("levels/l_05.json");
        return assets;
    }
}
