
// This class is autogenerated by ./autogen_res.py.
class AssetsList
{
    // Autogen'ed ... don't touch.
    static listGfx(){
        let assets = new Array();
        assets.push("gfx/sign_danger.png");
        assets.push("gfx/turtle.png");
        assets.push("gfx/turtle_in_shell_r0.png");
        assets.push("gfx/squished.png");
        assets.push("gfx/spring_jump_up.png");
        assets.push("gfx/bomb.png");
        assets.push("gfx/block_fall_on_touch_damaged_02.png");
        assets.push("gfx/block_pushable.png");
        assets.push("gfx/cloud.png");
        assets.push("gfx/button_floor.png");
        assets.push("gfx/bg-forest.png");
        assets.push("gfx/vampire_wannabe.png");
        assets.push("gfx/stompy.png");
        assets.push("gfx/platform_left_right.png");
        assets.push("gfx/gorilla_projectile.png");
        assets.push("gfx/tombstone.png");
        assets.push("gfx/flying_fire.png");
        assets.push("gfx/jumpee.png");
        assets.push("gfx/l0_splash.png");
        assets.push("gfx/bomb_started.png");
        assets.push("gfx/lava.png");
        assets.push("gfx/block_fall_on_touch.png");
        assets.push("gfx/canon_horizontal.png");
        assets.push("gfx/sphere_within_sphere.png");
        assets.push("gfx/explosion_big.png");
        assets.push("gfx/bush_branch.png");
        assets.push("gfx/elephanko_mad.png");
        assets.push("gfx/button_floor_pressed.png");
        assets.push("gfx/stars_black_sky.png");
        assets.push("gfx/spring_jump_up_extended.png");
        assets.push("gfx/elephanko.png");
        assets.push("gfx/doggy.png");
        assets.push("gfx/pants_gorilla_l0.png");
        assets.push("gfx/explosion_small.png");
        assets.push("gfx/ground_lr.png");
        assets.push("gfx/fancy_city_dweller.png");
        assets.push("gfx/canon_horizontal_shoot_soon.png");
        assets.push("gfx/hero_r0.png");
        assets.push("gfx/wood_texture.png");
        assets.push("gfx/mr_spore.png");
        assets.push("gfx/bomb_ignited.png");
        assets.push("gfx/block_level_transition.png");
        assets.push("gfx/brick_gray_bg.png");
        assets.push("gfx/turtle_in_shell_l0.png");
        assets.push("gfx/door_next_level_wide.png");
        assets.push("gfx/turtle_in_shell.png");
        assets.push("gfx/unknown.png");
        assets.push("gfx/fancy_city_dweller_hat.png");
        assets.push("gfx/canon_bullet_left.png");
        assets.push("gfx/spikes.png");
        assets.push("gfx/ground_lr2.png");
        assets.push("gfx/spike_ceiling.png");
        assets.push("gfx/block_fall_on_touch_damaged.png");
        assets.push("gfx/fountain.png");
        assets.push("gfx/turtle_r0.png");
        assets.push("gfx/sign_its_safe.png");
        assets.push("gfx/door_next_level.png");
        assets.push("gfx/spike_ceiling_falling.png");
        assets.push("gfx/smoke_dust.png");
        assets.push("gfx/bush_stackable.png");
        assets.push("gfx/magic_potion.png");
        assets.push("gfx/pants_gorilla_r0.png");
        assets.push("gfx/rabbit_house.png");
        assets.push("gfx/augustus_of_prima_rabitta.png");
        assets.push("gfx/hero_l0.png");
        assets.push("gfx/turtle_l0.png");
        assets.push("levels/l_00_rabbit_in_house.json");
        assets.push("levels/l_01.json");
        assets.push("levels/l_02_vampire_weekend.json");
        assets.push("levels/l_exp.json");
        assets.push("levels/l_05.json");
        assets.push("levels/l_02.json");
        assets.push("levels/l_04.json");
        assets.push("levels/l_03.json");
        assets.push("levels/l_99_rabbit_in_safe_house.json");
        assets.push("levels/gorilla.json");
        assets.push("levels/l_bug_stomp.json");
        return assets;
    }

    // Not Autogen'ed. Manually edit from .py file.
    //
    // Do not load with game, just load as go since bigger and game
    // can start without music.
    static listMusic() {
        let music = new Array();

        music.push('sounds/music/incompetech/delightful_d.ogg');
        music.push('sounds/music/incompetech/twisting.ogg'); // Moody, good for cave.
        music.push('sounds/music/incompetech/pookatori_and_friends.ogg');
        music.push('sounds/music/incompetech/getting_it_done.ogg');
        music.push('sounds/music/incompetech/robobozo.ogg');
        music.push('sounds/music/incompetech/balloon_game.ogg');
        music.push('sounds/music/incompetech/cold_sober.ogg');
        music.push('sounds/music/incompetech/salty_ditty.ogg');
        music.push('sounds/music/incompetech/townie_loop.ogg'); // Very peaceful, flute.
        music.push('sounds/music/incompetech/mega_hyper_ultrastorm.ogg'); // Super energetic. Maybe for special.
        // Legacy
        music.push('sounds/music/music_peaceful_contemplative_starling.ogg');
        music.push('sounds/music/twinmusicom_8_bit_march.ogg');
        music.push('sounds/music/twinmusicom_nes_overworld.ogg');
        music.push('sounds/music/music_juhanijunkala_chiptune_01.ogg');

        return music;
    }

    // Not autogenerated.
    static listLevels(){
        let levels = new Array();
        if (Constants.isDebug()) {
            levels.push('levels/l_02.json');
            levels.push('levels/gorilla.json');
            levels.push('levels/l_04.json');
        } else {
            levels.push('levels/l_00_rabbit_in_house.json');
            levels.push('levels/l_01.json');
            levels.push('levels/l_02.json');
            levels.push('levels/l_02_vampire_weekend.json');
            levels.push('levels/l_03.json');
            levels.push('levels/l_04.json');
            levels.push('levels/l_05.json');
            levels.push('levels/l_99_rabbit_in_safe_house.json');
        }

        return levels;
    }
}
