// This class is autogenerated by ./gen_res.py.
class AssetsList {
    static list() {
        let assets = new Array();
        assets.push("gfx/water.png");
        assets.push("gfx/block_bounce_right.png");
        assets.push("gfx/unknown.png");
        assets.push("gfx/tree_02.png");
        assets.push("gfx/brick.png");
        assets.push("gfx/tree_01.png");
        assets.push("gfx/doggy.png");
        assets.push("gfx/hero_r0.png");
        assets.push("gfx/block_special_red.png");
        assets.push("gfx/background.png");
        assets.push("gfx/hero_l0.png");
        assets.push("gfx/water_full.png");
        assets.push("gfx/next_level.png");
        assets.push("gfx/ball.png");
        assets.push("gfx/block_bounce_up.png");
        assets.push("gfx/castle.png");
        assets.push("gfx/tombstone.png");
        assets.push("gfx/background_end.png");
        assets.push("gfx/brick_fallout.png");
        assets.push("gfx/block_special_blue.png");
        assets.push("gfx/block.png");
        assets.push("levels/l_01.json");
        assets.push("levels/huge.json");
        assets.push("levels/l_00.json");
        return assets;
    }
}